/* 
 * ===========================================================================
 * File Name CashBakConstantEnum.java
 * 
 * Created on Apr 7, 2016
 *
 * This code contains copyright information which is the proprietary property
 * of CashBak-FI. No part of this code may be reproduced, stored or transmitted
 * in any form without the prior written permission of CashBak-FI.
 *
 * Copyright (C) CashBak-FI. 2017
 * All rights reserved.
 *
 * Modification history:
 * $Log: CashBakConstantEnum.java,v $
 * ===========================================================================
 */

package com.property.buyer.utility;

/**
*  This is a enum class related to cashback application.
* 
* @author mukeshs 
* @version 1.0 - Apr 7, 2016
*/
public enum CashBakConstantEnum {
	REGISTER("register"),
	UPLOAD_LOGO_TYPE("changeLogo"), 
	UPLOAD_PROFILE_PIC_TYPE("changeProfilePic"), 
	CELL_PHONE_PROVIDER_TYPE("CP"),
	EXPENSES_SOURCE_TYPE("EXPSRC"),
	INCOME_SOURCE_TYPE("INCSRC"), 
	POLICY("POLICY"),
	INCOMPLETE("INCOMPLETE"),
	REFUSED("REFUSED"),
	INPROGRESS("INPROGRESS"), 
	COMPLETE("COMPLETE"), 
	PERSONAL("PERSONAL"),
	CONTACT("CONTACT"), 
	EMPLOYMENT("EMPLOYMENT"),
	EMPLOYMENT_SMALL("Employment"),
	BANK("BANK"),
	BANK_NAME("bankName"),
	BANK_ADDRESS("bankAddress"),
	VERIFICATION("VERIFICATION"),
	COLLATERAL("COLLATERAL"), 
	INCOME("INCOME"),
	EXPENSE("EXPENSE"), 
	REFERENCE("REFERENCE"), 
	COSIGNER("COSIGNER"),
	APPROVED("APPROVED"),
	UNAPPROVED("DECLINED"), 
	UNDER_REVIEW("UNDERREVIEW"),
	CLEARED("CLEARED"), 
	UNCLEARED("UNCLEARED"),
	DATA_RELATED_TO_PMTCOMPLETEDAPP("PMTCOMPLETEDAPP"),
	DATA_RELATED_TO_PMTHISTORYDTLS("PMTHISTORYDTLS"),
	DATA_RELATED_TO_LOANAPPROVAL("LOANAPPROVAL"),
	DATA_RELATED_TO_CLEAREDLOAN("CLEAREDLOAN"),
	DATA_RELATED_TO_UNCLEAREDLOAN("UNCLEAREDLOAN"), 
	DATA_RELATED_TO_LOANDECLINED("LOANDECLINED"),
	ROW_DMVFEE("DMVFEE"), ROW_APPFEE("APPFEE"),ROW_FEE("FEE"),
	ROW_BALANCE("BALANCE"),
	STORE_APP("STORE"),
	WEBSITE_APP("WEBSITE"),
	ONLINE_REPORT("Online Application"), 
	STORE_REPORT("Store Application"),
	TOTAL_REPORT("Total Application"),
	PERCENT_ONLINE_REPORT("Percent Online Application"),
	PERCENT_STORE_REPORT("Percent Store Application"),
	PERCENT_TOTAL_REPORT("Percent Total Application"),
	APP_VOLUME_REPORT("AVR"),
	LOAN_VOLUME_REPORT("LVR"),
	CONVERSION_RATE_REPORT("CRR"),
	RISK_GRADE_TREND_REPORT("RGTR"),
	FIRST_PAY_DEFAULTS_REPORT("FPDR"),
	RISK_SCORE_KS_CHART("RSKC"),
	Actualvs_Expected_Bad_Ratesby_Risk_Score("AEBRR"),
	APP_VOLUME_REPORT_PAGE("appVolumeReport"), 
	LOAN_VOLUME_REPORT_PAGE("loanVolumeReport"),
	CONVERSION_RATE_REPORT_PAGE("convRateReport"),
	RISK_GRADE_TREND_REPORT_PAGE("riskGradTrendReport"),
	NUMBEROF_APP("Number of Applications"),
	NUMBEROF_LOAN("Number of Loans"),
	PERCENTOF_CONVERTED_APP("Percent of Converted Applications"),
	APPVOLMAP("appVolMap"), 
	LOANVOLMAP("loanVolMap"),
	NUMOFAPPMAP("numOfAppMap"), 
	NUMOFLOANMAP("numOfLoanMap"),
	NUMOFNEWAPPMAP("numOfNewAppMap"),
	FIRSTPAY("firstPayDefault"),
	RISK_GRADE_TREND_REPORT_APP_LOAN_VOL("ALVRGTR"),
	NUMBEROF_DECLINED_APP("Number of Declined Apps"), 
	NUMBEROF_REFUSED_APP("Number of Apps Refused by customer"), 
	NUMBEROF_NEWLOAN_ORGINATED("Number of New Loans Originated"), 
	PERCENTOF_NEWLOAN_ORGINATED("Percent of New Loans Originated"), 
	APPROVAL_RATE("Apporval Rate by Risk Grade"), 
	ACCEPTANCE_RATE("Acceptance Rate by Risk Grade"),
	PERCENT_OF_APPLICATIONS("Percent of Applications"),
	
	NEWLOANS_MADEBY_CAP("New Loans Made by Capacity"),   
	FIRSTPAY_DEFAULTBY_CAP("First Pay Defaults by Capacity"), 
	NEWLOAN_MIXBY_CAP("New Loan Mix by Capacity"),     
	FIRSTPAY_DEFAULT_RATEBY_CAP("First Pay Default Rate by Capacity"),   
	NEWLAONS_MADEBY_RISKGRADE("New Loans Made by Risk Grade"),          
	FIRSTPAY_DEFAULTSBY_RISKGRADE("First Pay Defaults by Risk Grade"),  
	NEWLOAN_MIXBY_RISKGRADE("New Loan Mix by Risk Grade"),  
	FIRSTPAY_DEFAULT_RATE_RISKGRADE("First pay Default Rate by Risk Grade"), 
	GOOD_VS_BAD_SCORE_DISTRIBUTION("Good vs Bad Score Distribution"),
	Actualvs_Expected_Bad_Ratesby_Risk_Score_60DPD("Actual vs Expected Bad Rates by Risk Score 60DPD"),
	ON("ON"),OFF("OFF"),SERVICE_SWITCH_UPDATED("Service Switch Updated Successfully"),
	SCHEDULED_PAYMENT("Scheduled Payment"),
	INTEREST("Interest"),LATE_FEE("Late Fee"),
	PLUS("+"),OPEN_PARANTHESIS("("),
	FULL_TIME("FULL TIME"),
	CLOSE_PARANTHESIS(")"),
	BLANK_SPACE(" "),
	DOUBLE_SPACE("  "),
	FOR_SCHEDULED_DATE("for Scheduled date"),
	TOTAL_AMOUNT_DUE("Total Amount Due"),
	IS("is"),
	YOUR_DUE_PMT("your due payment"),
	HI("Hi"),
	COMMA(","),
	DOLLAR("$"),
	LOAN_OUTSTANDING_LIST("loanOutStandingList"),
	TOTAL_BAL_ON_SCHDLD_DTE("totalBalOnSchdldDte"),
	TOT_SCH_BAL_STOREWISE_MAP("totSchBalStoreWiseMap"),
	SMS("SMS"),
	EMAIL("E-mail"),
	EMAIL_CAPS("EMAIL"),
	AND("and"),
	HAS_BEEN_SENT("has been sent."),
	RECORD_NOT_FOUND("Record not found for today"),
	UNABLE_TO_SEND_MSG("Unable to send message"),
	STATIC_POOL_60PLUS_PAST_DUE("Static Pool 60+ Days Past Due"), 
	STATIC_POOL("SP"), 
	STATIC_POOL_COMPLETE("Static Pool Complete"),
	SAMPLE_COLLECTION("SC"),
	SAMPLE_COLLECTIONS_REPORT("Sample Collections Report"), 
	COLLECTION_TREND_REPORT("Collections Trend Report"),

	TOTAL_SCH_BAL("totalSchBal"),
	TOTAL_PAST_DUE_AMT("totalPastDueAmt"),
	TOTAL_LAST_PMT_AMT("totalLastPmtAmt"),
	TOTAL_ORIGINAL_AMT("totalOriginalAmt"),
	TOTAL_LOAN_AMT("totalLoanAmt"),
	TOTAL_PAYOFF_AMT("totalPayoffAmt"),
	APPLY_LOAN("applyLoan"),
	CUSTOMER_LOOKUP("customerLookup"),
	SUCCESS("success"),
	PRINT_CUSTOMER_DETAIL("printCustomerDetail"),
	IS_PAYMENT_OUTSTANDING("isPaymentOutstanding"),
	CUSTOMER_SUMMARY("customerSummary"),
	CP_LOOKUPS("cpLookups"),
	CP_VALUE_LIST("cpValueList"),
	W("W"),
	PERSONAL_INFORMATION("personalInformation"),
	TRUE("true"),
	TASK_LIST("taskList"),
	TOTAL_INCOME("totalIncome"),
	TOTAL_EXPENSE("totalExpense"),
	NET_INCOME("netIncome"),
	CUST_NOT_FOUND("Customer not found with this Id : "),
	DEBIT_CARD_ENCRYPTED_VALUE("XXXX-XXXX-XXXX-"),
	GLOBAL_ERROR("globalError"),
	FIRST_ADD_LEAD_THEN_CLICK("first add lead by clicking Assign lead to employee then save it"),
	FAILURE("failure"),
	TAB_NAME("tabName"),
	VIEW_ADMIN_PANEL("viewadminpanel"),
	ASSIGNED_LEADS("assignedLeads"),
	VALID("valid"),
	INVALID("invalid"),
	TO_DO_LIST("toDoList"),
	M("M"),
	J("J"),
	K("K"),
	L("L"),
	Y("Y"),
	B("B"),
	X("X"),
	A("A"),
	C("C"),
	D("D"),
	N("N"),
	E("E"),
	SIX("6"),
	MIN_LOAN_AMOUNT("minLoanAmount"),
	LOAN_APPROVAL("loanApproval"),
	LOAN_DECLINED("loanDeclined"),
	CHANGE_APP_STATUS("changeAppStatus"),
	LOAN_APP_WITH_CUST_ID("Loan Application with customer Id :"),
	SENT_UNDER_REVIEW(" has been sent under review."),
	LOAN_APPROVAL_DETAILS_SENT("Loan Docs has been sent to customer Id : "),
	COLON(":"),
	BACK_SLASH_DOUBLE("\\"),
	FORWARD_SLASH_SINGLE("/"),
	CASHBAK_LOAN_DOC("CashBak_Loans_Doc_"),
	UNDER_SCORE("_"),
	PDF_EXTNSN(".pdf"),
	LOAN_DENIAL_DOC_SENT("Loan Docs has been sent to customer Id : "),
	LOAN_HAS_BEEN_DECLINED("Loan Application has been declined for customer id : "),
	CASHBAK_DOC("CashBak_Doc_")	,
	LEFT("left"),
	RIGHT("right"),
	CENTER("center"),
	HYPHEN("-"),
	LETTER("Letter"),
	MAIL("Mail"),
	RECEIVED_BY("Received By"),
	SIGNATURE("Signature"),
	EXCEPTION_CAUGHT("Exception Caught ::"),
	LOGO_DIR("logo"),
	LOGO_IMG_NAME("logo.png"),
	UNABLE_TO_FIND_LOGO_IMG("unable to find logo Image in classpath: "),
	ADDRESS("Address"),
	CELL_PHONE("Cell Phone"),
	DEAR("Dear"),EMPTY_STRING(""),
	PF("PF"),
	RECORD_UPDATED_SUCCESSFULLY("Record updated successfully with customer Id : "),
	RECORD_SAVED_SUCCESSFULLY("Record Saved successfully with customer Id : "),
	HASH("#"),
	BLANK("blank"),
	JPG("JPG"),
	REFF_UPLOAD_CUSTOMER_ID("reffUploadCustomerId"),
	REFF_UPLOAD_LOAN_ID("reffUploadLoanId"),
	UPLOAD_URL("uploadUrl"),
	UPLOAD_EDIT_ID("uploadEditId"),
	SHOW_SEND_UPLOAD_LINK_BTN("showSendUploadLinkBtn"),
	UNSECURE_FILE_UPLOAD_LIST("unSecureFileUploadList")
	,UPLOAD_DOCS("uploadDocs"),
	CONTENT_DISPOSITION("Content-Disposition"),
	SORRY_FILE_NOT_EXIST("Sorry!! The file you are looking for, doesn't exist"),
	LOAN_DOC_SELF_VERI_URL("loanDocSelfVeriUrl"),
	REFF_LOANDOC_SELF_VERI_CUSTOMERID("reffloanDocSelfVeriCustomerId"),
	LOANDOC_SELF_VERI_ID("loanDocSelfVeriId"),
	LOANDOC_SELF_VERIFI_LIST("loanDocSelfVerifiList"),
	LOANDOC_SELF_VERI("loanDocSelfVeri"),
	APPS_AND_LOAN_BY_MONTH("Apps and Loan by Marketing Channel for Month"),
	APPS_AND_LOAN_BY_MARKETING("AALBM"),
	GMIFAIURE("GMIFailure"), NETINCOMEFAILURE("NetIncomeFailure"), 
    COLLFAILURE("CollFailure"), 
    NOVINTAGEADDED("NoVintageAdded"),
    TRANSACTIONREPORT("Transaction Report"),
    TRANSACTION_REPORT("TR"),
    SECURE_FILE_UPLOAD_LIST("secureFileUploadList"),
    ONECASEFAILMSGFORCOLL("LOAN DENIAL - HOWEVER, 2 TESTS OF 3 PASS - SEEK POSSIBLE APPROVAL"),
    ONECASEFAILMSG("LOAN DENIAL - HOWEVER, 1 TESTS OF 2 PASS - SEEK POSSIBLE APPROVAL"),
    LOANDENIAL("LOAN DENIAL"),
    LOANAPPROVAL("LOAN APPROVAL"),
    RECOMMENDATION("RECOMMENDATION ---> "),
    NAME("name"),
    DOB("dob"),
    CASHBAK_CONFIRMATION_DOC_DIR("Cashbak Confirmation Doc"),
    PDF_SMALL_TEXT("pdf"),
    LOAN_APR_INFO_DOC_FORM("loanAprInfoDocForm"),
    UNABLE_TO_SEND_LOAN_DOC("Phone No. / E-mail not found, Unable to send Loan Docs to customer Id :"),
    SMS_SMALL("sms"),
    EMAIL_SMALL("email"),
    CALL_OR_PROMISE_LIST("callOrPromiseList"),
    RECORD_SAVED("Record Saved Successfully"),
	PORTFOLIO_ANALYSISREPORT("Portfolio Analysis Report"),
	PORTFOLIO_ANALYSIS_REPORT("PAR"),
	LOAN_BALANCEANALYSIS("Loan Balance Analysis"),
	LOAN_BALANCE_ANALYSIS("LBA"),
    FAILED("failed"),
    PASSES("Passes"),
    FAILS("Fails"),
    MAXAMOUNT("maxAmount"),
    PERMISSIONJSON("permissionJson"),
    CHOOSE_STORE("chooseStore"),
    ADD_EMPLOYEE("addEmployee"),
    CHANGE_PASSWORD("changePassword"),
    ERROR_MSG("errorMsg"),
    SUCCESS_MSG("successMsg"),
    INVALID_OLD_PASS("Invalid old password."),
    PASS_CHANGED("Your password has been changed."),
    NEWPASS_CONPASS_NOT_MATCH("New password and confirm password not matched"),
    VIEW_EMPLOYEE("viewEmployee"),
    PAYMENT_TO_CUSTOMER("paymentToCustomer"),
    PAYMENT_FROM_CUSTOMER("paymentFromCustomer"),
    VIEW_PAYMENT_HISTORY("viewPaymentHistory"),
    VIEW_PAYDAY_LOAN_HISTORY("viewPaydayLoanHistory"),
    VIEW_PAYMENT_COMPLETED_APP("viewPaymentCompletedApp"),
    VIEW_LOAN_OUTSTANDING("viewLoanOutstanding"),
    VIEW_SCH_OUTSTANDING("viewScheduleOutstanding"),
    SCHEDULEOUTSTANDINGTABLE("scheduleOutstandingTable"),
    ADD_ROLE("addRole"),
    VIEW_ROLE("viewRole"),
    CREATE_STORE("createStore"),
    VIEW_STORE("viewStore"),
    PMT_REVERT_MSG("Reverse Transaction "),
    CHECK_BOUNCED("Cheque Bounced"),
    VOID_PMT("void"),
    PENALTY("penalty"),
    CASH_PAYMENT_TYPE("Cash"),
    VIEW_REPORT_ALM("viewReportALM"),
    VIEW_REPORT_SC("viewReportSC"),
    VIEW_REPORT_TR("viewReportTR"),
    VIEW_REPORT_PAR("viewReportPAR"),
    VIEW_REPORT_LBA("viewReportLBA"),
    VIEW_REPORT_KS("viewReportKS"),
    VIEW_REPORT_AEB("viewReportAEB"),
    VIEW_REPORT("viewReport"),
    MONTH_FORMAT("MMM"),
    TOTAL_OS("Total os"),
	TOTAL_APP_IN(" (Total App)"),
	TOTAL_APP("Total App"),
	TOTAL_AMOUNT("Total Amount"),
	AMOUNT("Amount"),
	APP("App"),
	AVERAGE("Average"),
	FP_800("800"),
	FP_600_TO_799("600,799"),
	FP_400_TO_599("400,599"),
	FP_200_TO_399("200,399"),
	FP_0_TO_199("0,199"),
	FP_MINUS_200_TO_MINUS_1("-200,-1"),
	FP_MINUS_400_TO_MINUS_199("-400,-199"),
	FP_MINUS_400("-400"),
	GOODMAP("goodMap"),
	BADMAP("badMap"),
	SPC("SPC"),
	BOOKED_AMOUNT("$ Booked Amount"),
	SIXTYPLUS_DOLLAR("$ 60+"),
	OUTSTANDING_AMOUNT("$ Outstanding Amount"),
	OUTSTANDING_AMOUNT_PERCENT("% Outstanding Amount"),
	SIXTYPLUS_PERCENT("$ 60+ %"),
	APP1("app"),
	AMOUNT1("amount"),
	WITHIN_0_DAYS("WithIn 0 Days"),
	WITHIN_1_5_DAYS("WithIn 1 To 5 Days"),
	WITHIN_6_10_DAYS("WithIn 6 To 10 Days"),
	WITHIN_11_20_DAYS("WithIn 11 To 20 Days"),
	WITHIN_21_29_DAYS("WithIn 21 To 29 Days"),
	WITHIN_30_59_DAYS("WithIn 30 To 59 Days"),
	WITHIN_60_89_DAYS("WithIn 60 To 89 Days"),
	WITHIN_90_114_DAYS("WithIn 90 To 114 Days"),
	WITHIN_115_120_DAYS("WithIn 115 To 120 Days"),
	GROUP("Group"),
	WITHIN_O_1_MONTH("0-1 Month"),
	WITHIN_2_3_MONTH("2-3 Months"),
	WITHIN_4_MONTH("4 Months"),
	WITHIN_5_6_MONTH("5-6 Months"),
	WITHIN_7_12_MONTH("7-12 Months"),
	WITHIN_13_18_MONTH("13-18 Months"),
	WITHIN_19_24_MONTH("19-24 Months"),
	NOT_DUE("Not Due"),
	_30_DAYS("30 Days"),
	_60_DAYS("60 Days"),
	_90_DAYS("90 Days"),
	_120_DAYS("120 Days"),
	TOTAL_BALANCE("Total Balance"),
	_TOTAL("Total"),
	APP_MAP("appMap"),
	AMOUNT_MAP("amountMap"),
	CLOSING_PARANTHESES_BLANK(" ) "),
	OPENING_PARANTHESES(" ( "),
	AMT_PAID("amtPaid"),
	INTEREST_AMT_PAID("interestAmtPaid"),
	lATEFEE("lateFee"),
	WAIVE_FEE("waiveFee"),
	FROMDATE("fromDate"),
	TODATE("toDate"),
	LOANTYPE("loanType"),
	PMTTYPE("pmtType"),
	FYEAR("fYear"),
	TYEAR("tYear"),
	RECORD_ADD_THROUGH("recordAddThrough"),
	EMPNAME("empName"),
	LOANAPPROVALSTATUS("loanApproveStatus"),
	YEAR("year"),
	MONTH("month"),
	APP_STATUS("appStatus"),
	IS_CLEARED("isCleared"),
	FFIRSTPAYD("ffirstPayd"),
	TFIRSTPAYD("tfirstPayd"),
	CURR_DATE_SQL("currDateSql"),
	CUSTOMER_ID("customerId"),
	CURRENT_DATE("currentDate"),
	CUST_ID("custId"),
	VINTAGE_ID_VALE("vintageId"),
	VINTAGE("vintage"),
	EMPLOYEE_VALUE("employee"),
	UNDEFINED_VALUE("undefined"),
	TEMPORARY_PASSWORD_TEXT(" this is your temporary password "),
	PASSWORD_CHECK_LINK("     Please click on this link to login and change your password .. !</p><a href="),
	PASSWORD_LOGIN_TEXT(">Login</a>"),
	MESSAGE_PARAGRAPH("<p>Hi "),
	NEXT_LINE_VALUE(". </br>"),
	FORGOT_PASSWORD_MESSAGE("We have sent temporary password on your registered email id"),
	FORGOT_MAIL_KEY_VALUE("mailSuccessMsg"),
	MAIL_DOES_NOT_EXIST("Email ID not exist"),
	LOGGED_OUT_SUCCESSFULLY("You have been logged out successfully."),
	LOGIN("login"),
	LOGOUT("logout"),
	FORGOT_PASSWORD_TEXT("forgotPassword"),
	CUSTOMER_SMS_TEXT("Full Paid Statement has been sent to customer Id :: "),
	CUSTOMER_RECORD_NOT_FOUND("Record Not Found"),
	CUSTOMER_LAST_STMT_DETAILS("Last Four Paid Statements has been sent to customer Id :: "),
	STMT_DATE_MESSAGE("Statement of Date : "),
	CUSTOMER_CONFORMATION_MESSAGE_TEXT(" has been sent to customer Id :: "),
	SPECIFIC_SMS_PDF_CUSTOMER("Thanks for choosing Cashbak Loans, Please find your full Statement  "),
	CASH_BAK_THANKS_MESSAGE("Thanks for choosing Cashbak Loans, Please find the Statement for your last four payments "),
	DATE_TEXT("Date"),
	DESCRIPTION_TEXT("Description"),
	BALANCE_SMALL_TEXT("Balance"),
	STORE_HASH_TEXT("Store#"),
	WAIVE_FEE_TEXT("Waive Fee"),
	LATE_PAYMENT_LESS_FEE("Less Payment Late Fee"),
	PAYMENT_TEXT("Payment"),
	CASH_BAK_PDF_PAID_STMT("CashBak_FullPaid_Statement_"),
	INTREST_PAYMENT_TEST("Interest Payment"),
	MOTHLY_STMT_CUSTOMER("Monthly statements has been sent to all customers for statement date :: "),
	CHECK_PAYMENT_TYPE("Cheque"),
	UPDATE_EMP_PROFILE("updateEmpProfile"),
	UPDATE_EMP_PFORM("updateEmpPForm"),
	COMPANY_LOGO("companyLogo"),
	EMP_IMAGE("empImage"),
	ADDNEW_EMP_IMAGE("addNewEmpImage"),
	APPLY_LOANTAB_T("applyLoanTab_T"),
	LOAN_AMOUNT("LOAN AMOUNT"),
	DMV_FEE("DMV FEE"), 
	APP_FEE("APP FEE"),
	FEE("FEE"),
	INSURANCE_IMAGES("insuranceImages"),
	CHEQUE_URL("/Check_Details/paymentFromCustomerForm/"),
	PAID_DMV_FEE("paidDMVFee"),
	PAID_APP_FEE("paidAppFee"),
	ADD_EXPENSE_INFO_MSG("first add expenses info by clicking plus button then save it"),
	ADD_PERSONAL_INFO_MSG("First add Personal Information"),
	AND_OTHER("&other"),
	AND_OTHERS("&others"),
	AND_SIGN("&"),
	OPENING_PARANTHESIS_BLANK(" ("),
	CLOSING_PARANTHESIS(")"),
	PART_TIME("PART TIME"),
	NO_EMPLOYMENT("NO EMPLOYMENT"),
	COLLATERAL_INSUINFO_DOCFORM("collateralInsuInfoDocForm"),
    INSUINFO_DOCFORM("InsuInfoDocForm"),
    INSTALLMENT_LOANS("Installment Loans"),
    SIGNATURE_LOANS("Signature Loans"),
	PAYDAY_LOANS("Payday Loans"),
	TITLE_LOANS("Title Loans"),
	LOCAL_DRIVE("localDrive"),
	UTF_8("UTF-8"),
	APP_OCTET_STREAM("application/octet-stream"),
	MM_DD_YYYY("MM/dd/yyyy"),
	YYYY_MM_DD("yyyy/MM/dd"),
	DOUBLE_BACK_SLASH_S("\\s"),
	SEMICOLON_DOUBLE_FORWARD_SLASH("://"),
	SEMICOLON(":"),
	FORWARD_SLASH("/"),
	ALREADY_LOGIN("alreadylogin"),
	AUTHFAILED("authfailed"),
	INVALID_USER_NAME_OR_PASSWORD("Invalid User Name or Password"),
	ROLE("role"),
	DELETE("delete"),
	ROLELIST("roleList"),
	ROLEFORMBEAN("roleFormBean"),
	HEADER1("attachment; filename=\"%s\""),
	FILE_NOT_EXIST("Sorry. The file you are looking for does not exist"),
	RES_HEADER("inline; filename=\""),
	FORWARD_SLASH_QUOTE("\""),
	COLOR_TYPE("CL"),
    REDIRECT_TO_CHOOSE_STORE("redirect:/cash/choosestore"),
	BR1("<br/>"),
	BR2("<br/><br/>"),
	BR4("<br/><br/><br/><br/>"),
	NEW_LINE2("\n\n"),
	TOKEN_ID("?tokenId="),
	SESSIONEXPMSG("sessionExpMsg"),
	SESSION_EXP_MSG("Your Session has been expired."),
	LOGO_IMAGE_NOT_FOUND_MSG("unable to find logoImage in classpath: "),
	LOGO_FILE("/logo/logo.png"),
	SCHEDULE_FILE_NAME("CashBak_Payment_Installment_Schedule_"),
	PAYMENT_SCHEDULE("PAYMENT SCHEDULE"),
	NUMBER_OF_PAYMENT("# OF PAYMENT"),
	SCHEDULED_DATE("SCHEDULED DATE"),
	SCHEDULED_PAYMENT_AMOUNT("SCHEDULED PAYMENT $"),
	INTEREST_AMOUNT("INTEREST $"),
	FEES_AMOUNT("FEES $"),
	BALANCE_AMOUNT("BALANCE $"),
	NEW_LOAN("New Loan"),
	ZERO_DOUBLE_IN_STR("0.00"),
	APPLICATION_FEE("Application Fee"),
	DMV_FEE1("DMV Fee"),
	EXCEPTION_CAUGHT_INST("Exception Caught while sending installment schedule payment as email attachment  :: "),
	FALSE("false"),
	MULTIPLY_SIGN(" * "),
	SEMICOLON_DOLLAR(": $"),
	COMMA_SPACE(", "),
	EMPIMAGE("empImage"),
	SEMICOLON_FORWARDSLASH(":/"),
	CASHBAK_STATEMENT("CashBak_Statement_"),
	EXCEPTION_CAUGHT_WHILE_SENDING_FULL_STATMENT("Exception Caught while sending   full statement email :: "),
	CASHBAK_SPECIFICDATE_STATEMENT("CashBak_SpecificDate_Statement_"),
	DOUBLE_BACKSLASH_DOLLAR("\\$"),
	SCHEDULED_EMI_PAYMENT("Scheduled  EMI Payment"),
	STR_FORMAT("%.2f"),
	STATEMENT_DATE("Statement Date : "),
	TOTAL_AMOUNT_DUE_DOLLAR("Total Amount Due:  $"),
	DUE_DATE_SEMICOLON("Due Date : "),
	CELL_PHONE_("(Cell Phone) "),
	PAY_OFF_AMOUNT_AS_OF("* Pay off amount as of "),
	IS_DOLLAR("  is  $"),
	NEW_LOAN_AMOUNT("New Loan Amount"),
	DOLLAR_SPACE("$ "),
	APP_FEE_CAMELCASE("App Fee"),
	INTEREST_WITH_HYPHEN("Interest-"),
	MINUS_DOLLAR("-$ "),
	STORE("store"),
	ERROR_WHILE_DOWNLOAD_UNSECURE_UPLOADED_FILES("Error while download UnSecure Uploaded Files"),
	DATE_FORMAT3("EEE MMM dd HH:mm:ss z yyyy"),
	EXCEPTION_AFTER_HITTING_UPLOAD("Exception caught after hitting Upload Document URL  :: "),
	EXCEPTION_AFTER_HITTING_LOAN_DOC("Exception caught after hitting loan Doc Self Verification  URL  :: "),
	ERROR_WHILE_DOWNLOADFILES("Error while downloadFiles"),
	ERROR_WHILE_DOWNLOADLOANDOCURL("Error while downloadLoanDocUrl"),
	NEW_LINE1("\n"),
	BLANK_HYPHEN(" - "),
	LOAN_NUM("Loan # :"),
	LOAN_AMT("Loan Amt $ :"),
	LOAN_DATE("Loan Date :"),
	LOOKUP_EDIT_NAME("lookupEditName"),
	LOOKUP_EDIT_TYPE("lookupEditType"),
	LOOKUP_EDIT_VALUE("lookupEditValue"),
	LOOKUP_EDIT_MODE("lookupEditMode"),
	LOOKUP_EDIT_ID("lookupEditId"),
	VINTAGE_EDIT_MODE("vintageEditMode"),
	OLD_VINTAGE_NUMBER("oldVintageNumber"),
	DECLINE_REASON_NUMBER("lonaDeclineReasonId"),
	WEDNESDAY("Wednesday"),
	EEEE("EEEE"),
	STR_05("05"),
	STR_20("20"),
	STR_07("07"),
	STR_22("22"),
	STR_08("08"),
	STR_23("23"),
	STR_10("10"),
	STR_6("6"),
	STR_15("15"),
	STR_13("13"),
	STR_01("01"),
	STR_03("03"),
	STR_LAST("LAST"),
	STR_25("25"),
    STR_30("30"),
    STR_29("29"),
    SELECTED_DATE("selectedDate"),
    YES("yes"),
    CALL_OR_PROMISE("CALLS"),
    QUICK_SMS_EMAIL("QUICK SMS/E-MAIL"),
    BLOCK("BLOCK"),
    UNBLOCK("UNBLOCK"),
    LOAN_INFO("loanInfo"),
    CUST_BLOCK_DET("custBlockDetail"),
    START("start"),
    LENGTH("length"),
    DRAW("draw"),
    COL("col"),
    DELETED_APPS("deletedApps"),
    ITOTALRECORDS("iTotalRecords"),
    ITOTALDISPLAYRECORDS("iTotalDisplayRecords"),
    DATA("data"),
    LOANAPPROVALTABLE("loanApprovalTable"),
    LOANAPPROVEDTABLE("loanApprovedTable"),
    LOANDECLINEDTABLE("loanDeclinedTable"),
    CHANGEAPPSTATUSTABLE("changeAppStatusTable"),
    CUSTOMERLOOKUPTABLE("customerLookupTable"),
    TODOLISTTABLE("toDoListTable"),
    BLOCKCUSTDETTABLE("blockCustDetTable"),
    DELETEDAPPTABLE("deletedAppTable"),
    CALLPROMISEFORSTOREDTABLE("callPromiseforStoreDTable"),
    PAYMENTHISTORYTABLE("paymentHistoryTable"),
    PMTCOMPLETEDAPPTABLE("pmtCompletedAppTable"),
    PMTFROMCUSTTABLE("pmtFromCustTable"),
    LOANOUTSTANDINGTABLE("loanOutstandingTable"),
    PHONEMASK("+1(###)-###-####"),
    SEARCHVALUE("search[value]"),
    ORDERDIR("order[0][dir]"),
    ORDERCOL("order[0][column]"),
    ACTION("action"),
    ORDERBY(" order by "),
    DIVCLASS("<div class='no-wrap'> "),
    ENDDIV("</div> "),
    ASC("asc"),
    DESC("desc"),
    CONCATFIRSTLASTNAME("CONCAT(loanInfo.personalInformation.lastName,',', loanInfo.personalInformation.firstName)"),
    STOREIDFIELD("loanInfo.store.storeId"),
    LOANTYPEFIELD("loanInfo.loanType"),
    LOANIDFIELD("loanInfo.id"),
    CUSTIDFIELD("loanInfo.personalInformation.id"),
    APPSTATUSFIELD("loanInfo.appStatus"),
    SOURCEFIELD("loanInfo.recordAddThrough"),
    CREATEDONFIELD("loanInfo.createdOn"),
    EMAILFIELD("pInfoMail.email"),
    PHONEFIELD("contactNum.phoneNumber"),
    DOBFIELD("loanInfo.personalInformation.dob"),
    SSNFIELD("loanInfo.personalInformation.ssn"),
    DLNFIELD("loanInfo.personalInformation.dln"),
    APPROVESTATUSFIELD("loanInfo.loanApproveStatus"),
    REASONTODELETEFIELD("loanInfo.reasontodelete"),
    PERSONALLEAD("personalLead"),
    CONTACTLEAD("contactLead"),
    EMPLOYMENTLEAD("employmentLead"),
    BANKLEAD("bankLead"),
    VERIFICATIONLEAD("verificationLead"),
    COLLATERALLEAD("collateralLead"),
    INCOMELEAD("incomeLead"),
    EXPENSELEAD("expenseLead"),
    REFERENCELEAD("referenceLead"),
    COSIGNERLEAD("cosignerLead"),
    NOMILITARYDETAILS("NoMilitaryDetails"),
    MILITARYCHECKFAILS("MilitaryCheckFails"),
    LEAVE_BLANK("LEAVE BLANK"),
	ACKNOWLEDGEMENT("Acknowledgement"),
	NEED_MORE_INFO("Need More Info"),
	PAYDATE_CHANGE("Paydate Change"),
	WIRE_VS_CREDIT("Wire vs Credit"),
	COURTESY_REMINDER("Courtesy Reminder"),
	DEPOSIT_BINDER("Deposit Binder"),
	NEED_TO_SIGN_DOC("Need to Sign Doc"),
	FOLLOW_UP("Follow Up"),
	COLLECTIONS_CALLS("Collections Calls"),
	EMAILS("Emails"),
	LOAN_DECLINE("Loan Decline"),
	COMMENTS("Comments:"),
	STATUS("status"),
	BANK_ROUTING_NUMBER(" Routing# : "),
	MESSAGE("message"),
	BANK_MESSAGE("Bank Information with account# : "),
	BANK_INACTIVE(" is Inactive "),
	NO_LOAN_DETAILS("No loan details found with this loan Id"),
	NO_OUTSTANDING_SCHEDULE("No outstanding schedule found with this loan Id"),
	ELEVENAM("11:00 am"),
	THREEPM("03:00 pm"),
	MOBILE("mobile"),
	CUSTVERDETAIL("custVerDetail"),
	VERTYPEIDS("verTypeIds"),
	MM_DD_YYYY_HH_MM_SS("MM/dd/yyyy HH:mm:ss"),
	EMAILCASHBAKLINK("<a href='https://www.cashbackloans.com/' >Click Here</a>"),
	MOBILECASHBAKLINK("Click Here https://www.cashbackloans.com/"),
	SEND_LOAN_APPROVAL_PDF("Send Loan Approval Pdf"),
	SEND_LOAN_DECLINE_PDF("Send Loan Decline Pdf"),
	SEND_PMT_SCHEDULE("Send Pmt Schedule"),
	LOCKED("Locked"),UNLOCKED("Unlocked"),BOTH("Both"),
	PHONE_NUM("Phone Number"), PHONE_STATUS("Phone Status"),
	PHONE_PROVIDER("Phone Provider"),PHONE_TYPE("Phone Type"),
	ADDRESS_SINCE("Address Since"),
	ADDRESS1("Address1"),ADDRESS2("Address2"),
	ZIP("Zipcode"),CITY("City"),STATE("State"),
	ACTIVE("Active"),INACTIVE("Inactive"),ASSLOANTYPES("assLoanTypes"),OWN_RENT("Own / Rent"),
	GMI("GMI"),NET_INCOME_CAPS("NET INCOME"),ACTIVETAB("activeTab"),NOT_ACTIVE_MILITARY("NOT ACTIVE MILITARY"),CA("CA"),;

	private String value;

	CashBakConstantEnum(String value) {
		this.value = value;

	}

	public String getValue() {
		return value;
	}
}
